services:
  db:
    image: mongo:6.0
    container_name: db
    hostname: db
    env_file:
      - .mongoenv
    volumes:
      - dbdata:/data/db
    networks:
      - backend
  app:
    build: .
    hostname: app
    container_name: app
    links:
      - "db:portfolio-mongodb-headless"
    env_file:
      - .appenv
    depends_on:
      - db
    networks:
      - backend
      - frontend
  reverse_proxy:
    image: nginx:alpine-slim
    container_name: nginx
    hostname: nginx
    ports:
    - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./errors:/usr/share/nginx/html
    networks:
      - frontend

    depends_on:
      - app
volumes:
  dbdata:
networks:
  backend:
  frontend: